name: Cyber-Shield Bot 24/7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-main-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install discord.py firebase-admin

      - name: Start Shield Bot
        env:
          # כאן התיקון - הוא מושך את הטוקן מהשם הנכון ב-Secrets שלך
          DISCORD_TOKEN: ${{ secrets.CYBER_SHIELD_TOKEN }}
        run: python main.py

  run-alt-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install discord.py

      - name: Start Alt Detector
        env:
          DISCORD_TOKEN: ${{ secrets.ALT_BOT_TOKEN }}
        run: python alt_detector.py
